import { PosCategory, PosProduct } from './domain/pos';

import vinoTinto from '../../pos-icons/style-1/vino-tinto-copa.jpg';
import vinoBlanco from '../../pos-icons/style-1/vino-blanco-copa.jpg';
import vinoRosado from '../../pos-icons/style-1/vino-rosado-copa.jpg';

export const initialCategories: PosCategory[] = [
  {
    id: 'cat-bebidas',
    name: 'Bebidas',
    posPath: 'Barra/Bebidas',
    productPath: 'Bebidas/Refrescos',
    color: '#bc8fbb',
    sequence: 1,
  },
  {
    id: 'cat-vinos',
    name: 'Vinos',
    posPath: 'Barra/Vinos',
    productPath: 'Bebidas/Vinos',
    color: '#8190df',
    sequence: 2,
  },
  {
    id: 'cat-infusion',
    name: 'Infusiones',
    posPath: 'Barra/Infusiones',
    productPath: 'Bebidas/Infusiones',
    color: '#5bbeb3',
    sequence: 3,
  },
];

export const initialProducts: PosProduct[] = [
  {
    id: 'prod-coca-cola',
    categoryId: 'cat-bebidas',
    defaultCode: 'POS-REF-001',
    name: 'Coca-Cola',
    listPrice: 2.3,
    barcode: '841000000011',
    imageFile: '',
    imageSourcePath: '',
    imagePreviewUrl: '',
    imageStyle: '',
    sequence: 1,
  },
  {
    id: 'prod-agua',
    categoryId: 'cat-bebidas',
    defaultCode: 'POS-REF-002',
    name: 'Agua',
    listPrice: 1.5,
    barcode: '841000000012',
    imageFile: '',
    imageSourcePath: '',
    imagePreviewUrl: '',
    imageStyle: '',
    sequence: 2,
  },
  {
    id: 'prod-vino-tinto',
    categoryId: 'cat-vinos',
    defaultCode: 'POS-VIN-001',
    name: 'Vino Tinto',
    listPrice: 3.9,
    barcode: '841000000013',
    imageFile: 'vino-tinto-copa.jpg',
    imageSourcePath: 'style-1/vino-tinto-copa.jpg',
    imagePreviewUrl: vinoTinto,
    imageStyle: 'style-1',
    sequence: 1,
  },
  {
    id: 'prod-vino-blanco',
    categoryId: 'cat-vinos',
    defaultCode: 'POS-VIN-002',
    name: 'Vino Blanco',
    listPrice: 3.9,
    barcode: '841000000014',
    imageFile: 'vino-blanco-copa.jpg',
    imageSourcePath: 'style-1/vino-blanco-copa.jpg',
    imagePreviewUrl: vinoBlanco,
    imageStyle: 'style-1',
    sequence: 2,
  },
  {
    id: 'prod-vino-rosado',
    categoryId: 'cat-vinos',
    defaultCode: 'POS-VIN-003',
    name: 'Vino Rosado',
    listPrice: 3.9,
    barcode: '841000000015',
    imageFile: 'vino-rosado-copa.jpg',
    imageSourcePath: 'style-1/vino-rosado-copa.jpg',
    imagePreviewUrl: vinoRosado,
    imageStyle: 'style-1',
    sequence: 3,
  },
  {
    id: 'prod-te-verde',
    categoryId: 'cat-infusion',
    defaultCode: 'POS-INF-001',
    name: 'Te Verde',
    listPrice: 2.1,
    barcode: '841000000016',
    imageFile: '',
    imageSourcePath: '',
    imagePreviewUrl: '',
    imageStyle: '',
    sequence: 1,
  },
];

